### ISSUE TITLE
Error searching in WDS directory

### ISSUE THREAD

**Issue by fSergio101** [vivaxy/alfred-open-in-vscode#12]
# How to reproduce
- Install the workflow
- Give a path to `wds`  var.
- Type `code+<space bar>+<chars enough to trigger the search>`
- Then you get the error

```
[03:26:56.709] ERROR: Open in VSCode[Script Filter] JSON error: Garbage at end. in JSON:
{
	"items": []
}
{
	"items": [
		{
			"title": "TypeError: (intermediate value).flat is not a function\n    at getWds (/usr/local/lib/node_modules/alfred-open-in-vscode/index.js:23:5)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nTypeError: (intermediate value).flat is not a function\n    at getWds (/usr/local/lib/node_modules/alfred-open-in-vscode/index.js:23:5)\n```\n\n-\nOpen in VSCode 1.1.0\nAlfred 4.3.4\ndarwin 20.5.0",
				"largetype": "TypeError: (intermediate value).flat is not a function\n    at getWds (/usr/local/lib/node_modules/alfred-open-in-vscode/index.js:23:5)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

# Expected result

- Once I type chars enough to trigger the search I get the list of results in the Alfred search bar.

Could [latest commit](https://github.com/vivaxy/alfred-open-in-vscode/commit/66336b9703c4cf39fd994cd9bfd09473241f218f) that implemented `getWds` function be the reason of the bug?

**Comment by vivaxy** [comment]
`getWds` worked fine on Node.js v12.
What's your Node.js version?

**Comment by fSergio101** [comment]
`v12.22.3` I'm using `nvm` I'm not familiar with node, so consider it could be an issue of my local environment. Feel free to close the issue if it works 😉

**Comment by vivaxy** [comment]
Hi, @fSergio101. I'd like to make sure the correct version of Node.js is used. Could you please check node version with `> nvm ls default`?

**Comment by fSergio101** [comment]
```
> nvm ls default
       v14.17.3
```

**Comment by fSergio101** [comment]
changing the default as follows
```
> nvm alias default 12.22.3
default -> 12.22.3 (-> v12.22.3)
> nvm ls default
->     v12.22.3
```

it still happens anyway

**Comment by vivaxy** [comment]
@fSergio101 Hi, could you install the latest `alfred-open-in-vscode@1.3.1`, and type `code DEBUG` to see which node version is running?

**Comment by re-f** [comment]
I have come across the same problem the 
node version is 16.6.1
![image](https://user-images.githubusercontent.com/8351089/168476808-fd42432c-2ae6-4bf9-bb90-4c9e884d7867.png)
